@startuml



actor User as U
participant "Web Client" as C
participant "Lookst Server" as S
database "Lookst DB" as DB

title 공지사항

'공지사항 게시판 리스트
U -> C: 1.공지사항 게시판 리스트\nGET: [:/lookst/board/list/notice]

activate C
C -> S: static asset 요청 (HTML/CSS 등)

activate S
S -> DB : 공지사항 게시글 전체 리스트 DB 요청
activate DB
DB --> S : 공지사항 게시글 전체 리스트 DB 응답
deactivate DB
S --> C : HTML/CSS 응답
deactivate S

C --> U: 공지사항 게시판 리스트 출력
deactivate C

' 공지사항 게시판 읽기
U -> C: 2.공지사항 게시글 상세 페이지\nGET: [/lookst/board/read/notice]

activate C
C -> S: static asset 요청 (HTML/CSS 등)

activate S
S -> DB : 공지사항 게시글 DB select  요청
DB --> S :공지사항 게시글 DB select  응답
S --> C : HTML/CSS 응답
deactivate S

C --> U: 공지사항 게시글 출력
deactivate C
